-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 12, 2016 at 05:17 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.5.37

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `laps8561_hight`
--

-- --------------------------------------------------------

--
-- Table structure for table `barang`
--

CREATE TABLE `barang` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `brand` varchar(100) NOT NULL,
  `deskripsi` text NOT NULL,
  `stok` int(11) NOT NULL DEFAULT '0',
  `harga` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `diskon` int(3) UNSIGNED NOT NULL DEFAULT '0',
  `kategori_id` int(11) NOT NULL,
  `field_detail` text NOT NULL,
  `garansi` varchar(60) NOT NULL,
  `warna` varchar(255) NOT NULL,
  `gambar` text NOT NULL,
  `berat_gram` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `jumlah_lihat` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `status` int(11) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `barang`
--

INSERT INTO `barang` (`id`, `nama`, `brand`, `deskripsi`, `stok`, `harga`, `diskon`, `kategori_id`, `field_detail`, `garansi`, `warna`, `gambar`, `berat_gram`, `jumlah_lihat`, `status`) VALUES
(20, 'BETOP USB Vibration Controller Joystick', 'BETOP ', 'Nikmati pengalaman bermain game yang menyenangkan dengan menggunakan joystick dari BETOP ini, dengan desain yang ergonomis membuat anda nyaman dalam mengontrol permainan. Joystick dengan fitur getar membuat gameplay anda semakin menarik dalam memainkan game-game favorit anda. Gamepad mengusung penggunaan XD4 Game Engine yang membuat kontrol semakin stabil, frekuensi getar yang baik, dan transmisi yang kuat serta lancar dalam memainkan game.', 18, 145400, 0, 1, 'OMUAA3BK;USB;156 x 102 x 60 mm;None;', '1 bulan', 'Black', 'images/6.jpg', 1, 13, 1),
(21, '8Bitdo Super Wireless Gamepad Controller', '8Bitdo ', 'Gamepad ini memiliki bentuk yang sangat kecil dan dapat dijadikan gantungan kunci. Memiliki D-Pad dan 6 buah tombol untuk memainkan game-game kesukaan Anda. Dapat digunakan untuk untuk semua perangkat yang memiliki koneksi bluetooth.', 12, 372400, 0, 1, 'OMGA06WH;Bluetooth & USB connection;64 x 132 x 15 mm;Built-in 480mAh Li-on battery;', '1 bulan', 'White', 'images/4.jpg', 1, 12, 1),
(22, '8Bitdo Zero Mini Portable Bluetooth Gamepad', '8Bitdo ', 'Gamepad ini memiliki bentuk yang sangat kecil dan dapat dijadikan gantungan kunci. Memiliki D-Pad dan 4 buah tombol untuk memainkan game-game kesukaan Anda. Dapat digunakan untuk untuk semua perangkat yang memiliki koneksi bluetooth. Memiliki tombol D-Pad dan 4 buah tombol persis dengan gamepad pada umumnya. Dengan ini Anda dapat bermain game dimana saja dengan nyaman.', 3, 115900, 0, 1, 'OMGA03WH;Bluetooth 3.0;	14 x 12 x 11 cm;None;', '1 bulan', 'White', 'images/5a.jpg', 0, 12, 1),
(23, 'Dobe Bluetooth Wireless Gamepad Joystick', 'Dobe ', 'Gaming Controller Bluetooth / Wireless Gamepad membuat bermain game di iPhone dan smartphone semakin mudah nyaman dan menyenangkan. Dengan design yang dinamis seperti controller console membuat gaming hand grip ini wajib untuk para mania game mobile. Hanya dengan memasang iPhone atau smartphone ke gaming controller ini, Anda sudah dapat memainkan game kesukaan Anda. Tidak perlu menginstal aplikasi, baterai, dll.', 4, 162500, 0, 1, 'OMSCMUBK;Charging input;Support 5.5 Inch mobile phone;400MA/H;', '1 bulan', 'Black', 'images/7.jpg', 1, 12, 1),
(24, 'Ipega Gaming Console Hand Grip', 'Ipega ', 'iPega Gaming Controller membuat bermain game di iPhone semakin mudah nyaman dan menyenangkan. Dengan design yang dinamis seperti controller console membuat gaming hand grip ini wajib untuk para mania game mobile.', 5, 60800, 0, 1, 'IAIP03BK;-;-;-;', '1 bulan', 'Black', 'images/10.jpg', 1, 12, 1),
(25, 'Ipega Bluetooth Game Controller with TouchPad', 'Ipega ', 'Ipega PG-9028 is a new design wireless bluetooth controller with multimedia keys and support different Android / iOS / PC and etc games. You can put your Smartphone on this controller. The holder can be adjusted easily so it fits your Smartphone. Making this gaming controller more convenient for playing games. Compatible for most Virtual Reality Game and can be use as controller for Google Cardboard, Samsung Gear VR and other VR Box on the market.', 24, 281700, 0, 1, 'IATA06BK;Bluetooth;-;380mAh;', '1 bulan', 'Black', 'images/9.jpg', 1, 12, 1),
(26, 'Ipega Bluetooth Game Controller', 'Ipega ', 'Ipega PG-9023 is a new design wireless bluetooth controller with multimedia keys and support different Android / iOS / PC and etc games. Compatible with WinXP/Win7/Win8, Android Smartphone/Tablet, Android TV Box, Android TV and iOS. Compatible for most Virtual Reality Game and can be use as controller for Google Cardboard, Samsung Gear VR and other VR Box on the market.', 10, 338400, 0, 1, 'IATA07BK;Bluetooth;-;380mAh;', '1 bulan', 'Black', 'images/8.jpg', 1, 12, 1),
(27, 'Ipega The Son of Phantom Shox Blaster Bluetooth Gun Gamepad', 'Ipega ', 'Ipega PG-9057 hadir dengan bentuk pistol yang memberi pengalaman bermain game Anda lebih imersif dan berkesa terutama jika Anda bermain game FPS. Smartphone dapat Anda letak pada holder universal yang terdapat dibagian atas pistol dan terhubung via koneksi bluetooth.', 35, 299900, 0, 1, 'IATA0ABK;bluetooth;15 x 22 cm;Built-in battery capacity: 600mAh;', '1 bulan', 'Black', 'images/11.jpg', 2, 12, 1),
(28, 'VR Box Bluetooth Smartphone Controller', 'No brand', 'Gamepad ini memiliki bentuk yang kecil, sehingga dapat dioperasikan hanya dengan 1 tangan. Memiliki joystick dan 4 buah tombol untuk memainkan game-game kesukaan Anda. Sangat cocok digunakan bersama dengan Cardboard Virtual Reality.', 9, 27900, 0, 1, 'OMGA05BK;Bluetooth 3.0;118 x 33 x 42 mm;2 x AAA;', '1 bulan', 'hitam', 'images/2.jpg', 0, 12, 1),
(29, 'Xiaomi Bluetooth Gamepad Controller Joystick for Smartphone, Tablet, Smart TV & PC', 'Xiaomi', 'This thing comes with Bluetooth 3.0 connectivity, which basically allows you to connect it wherever you want, be it your smart TV, Android Box, smartphone, tablet, etc. Xiaomi has confirmed that this thing is compatible with Google’s Android OS, so you really should have no problem pairing this up with your device. Regarding its design, this thing resembles the Xbox controller a whole lot and it has a two built-in motors for better gaming experience.', 10, 274200, 0, 1, 'XOGA01BK;Bluetooth Ver3.0;156 x 104 x 65 mm;2 x AA batteries;', '1 bulan', 'hitam', 'images/1.jpg', 1, 12, 1),
(30, 'COGITO Pop Fashion Connected Watch', 'COGITO ', 'The newest connected watch from CONNECTEDEVICE Ltd debuts at CES 2014. Named as CES INNOVATIONS Design Award Honoree!\r\nCreated for maximum mainstream appeal, COGITO POP collection combines fun and functionality to make smartwatches accessible to a larger public with a more natural user experience.\r\nThe combination of the watch with its app provides essential notifications from the phone, visible at a glance to the wrist. COGITO POP has been named an International CES Innovations 2014 Design and Engineering Awards Honoree for Wireless Handset Accessories.\r\nProducts entered in this prestigious program are judged by a panel of independent expects to honor outstanding design and engineering in cutting edge consumer electronics products across 29 product categories. COGITO POP was designed expressly for active, social and connected crowd.', 3, 799000, 0, 2, 'CISM01RC;44 x 16.3 mm;', '1 bulan', 'Raspberry Crush', 'images/25.jpg', 1, 12, 1),
(31, 'Asus ZenWatch 2 Camel Leather Strap ', 'Asus ', 'ZenWatch 2 adalah smartwatch generasi terbaru dari line up ZenWatch Asus. hadir dengan design yang sangat nyaman digunakan, mudah di kostumasi dengan tali strap yang dapat dilepas pasang sesuai dengan life style Anda. Daya tahan baterai hingga 24 jam membuat jam ini sangat fungsional untuk digunakan dalam kegiatas sehari-hari. Jam tangan yang baik adalah jam tangan yang nyaman digunakan dan pas ditangan. Hadir dalam 2 buah ukuran yaitu 1.63" untuk pria dan 1.45" untuk wanita. Asus ZenWatch 2 mengkombinasikan style dan fitur canggih dalam pergelangan tangan Anda.', 18, 2499000, 0, 2, 'ASSM02SV;1.63";', '6 bulan', 'Brown', 'images/21.jpg', 0, 12, 1),
(32, 'U10 Smartwatch ', 'Uwatch', 'Smartwatch U10 untuk iOS dan Android. Smartwatch ini dilengkapi dengan berbagai macam fitur menarik seperti menjawab telepon secara langsung, tracking smartphone, pedometer, dll. Dengan design body yang modis, sangat cocok untuk dikenakan sehari-hari.', 1, 368900, 0, 2, 'OMSM03BK;41 x 47.9 x 9.18 mm;', '1 bulan', 'Black', 'images/27.jpg', 0, 12, 1),
(33, 'XBOX 360 USB Vibration Controller Joystick', 'XBOX ', 'Excellent conditioned USB PC Joystick, enjoy your PC game by this dual shock PC game controller. By using the Dual shock USB Joystick get vibration feedback when playing games. You can comfortably use the four trigger buttons on the top of the game pad with your first two fingers. Enjoy the realistic feeling while playing PC Game!', 30, 118600, 0, 1, 'OMUA8IBK;USB Port;17.0 x 13.0 x 4.0 cm;None;', '1 bulan', 'Black', 'images/3.jpg', 0, 12, 1),
(34, 'SKMEI Kids Monitoring Smartwatch LCD Screen', 'SKMEI ', 'Jam tangan dengan layar LCD ini memiliki fitur GPS dan SOS sehingga Anda dapat memantau posisi anak Anda saat sedang berpergian. Tombol SOS berfungsi untuk memberi notifikasi berupa panggilan telepon ke nomor tujuan yang terdapat. Jam ini memiliki slot kartu GSM sehingga dapat digunakan untuk bertelepon.', 7, 309300, 0, 2, 'EMSM02PN;52mm;', '1 bulan', 'Pink', 'images/251.jpg', 0, 13, 1),
(35, 'I-One U8 Smartwatch', 'I-One', 'SmartWatch U Watch U8 yang dikembangkan ini hadir untuk mempermudah koneksi antara Anda dengan orang-orang di sekitar Anda. U Watch U8 dirancang dengan desain yang revolusioner untuk dihubungkan dengan smartphone bersistem operasi Android. Memiliki layar sebesar 1.48" dengan tipe iPod Nano touch screen, smartwatch ini juga mendukung multi-bahasa (Inggris dan Cina). Tampil dengan User Interface HD menawan ber-icon besar, Anda pun dapat melakukan panggilan telepon, SMS serta fitur-fitur lain seperti pedometer, informasi cuaca, remote control kamera, alarm, kalendar, stopwatch, dan sebagainya.', 24, 88000, 0, 2, 'IO763OTAK517ANID-524254;1.48";', '1 Tahun', 'Black', 'images/30.jpg', 1, 12, 1),
(36, 'SKMEI Kids Monitoring Smartwatch', 'SKMEI ', 'Jam tangan dengan layar LCD ini memiliki fitur GPS dan SOS sehingga Anda dapat memantau posisi anak Anda saat sedang berpergian. Tombol SOS berfungsi untuk memberi notifikasi berupa panggilan telepon ke nomor tujuan yang terdapat. Jam ini memiliki slot kartu GSM sehingga dapat digunakan untuk bertelepon. Jam tangan dapat digunakan untuk komunikasi langsung dengan nomor tujuan yang terdaftar misalnya seperti nomor orang tua. Sehingga saat anak ingin berkomunikasi, maka dia cukup menekan tombol call dan jam akan otomatis menghubungi orang tua.', 16, 379100, 0, 2, 'EMSM03BL;54 x 34 mm;', '1 bulan', 'Cyan Blue', 'images/24.jpg', 0, 12, 1),
(37, 'SKMEI Smart LED Bluetooth Smartwatch', 'SKMEI ', 'Smartwatch dengan teknologi bluetooth untuk menghubungkan jam tangan dengan smartphone Anda. Anda dapat memonitor notifikasi, mengangkat telepon, terdapat kamera untuk foto, kalender reminder,  sport monitor, sleeping monitor dan fungsi-fungsi lainnya. Kompatibel dengan android dan ios.', 2, 321400, 0, 2, 'EMSM01BK;1.54";', '1 bulan', 'Black', 'images/23.jpg', 0, 12, 1),
(38, 'inWatch Pi ', 'inWatch ', 'Pi, this ancient and never ending number, here only represent a simple, pure, perfect circle. inWatch Pi symbolizes complex to simple deisgn, show full of natural beauty, enduring, always enjoy her accompany. 2032 replaceable coin cell, to cancel the display to reduce power consumption, standby for several months while easily open next journey. Fully enclosed professional-grade waterproofing, mechanical watches waterproof rating, underwater 30 meters do not have to worry about the watch when the machines. pi , can accompany you to go more places and do more things.', 6, 449900, 0, 2, 'IWSM01BK;35 x 35 x 7.8 mm;', '1 bulan', 'Black', 'images/26.jpg', 0, 12, 1),
(39, 'SKMEI Jam Tangan OLED Smartwatch Fitness', 'SKMEI ', 'Jam tangan gelang dari SKMEI ini selain berfungsi sebagai jam juga memiliki fitur-fitur notifikasi sms, email, telpon, monitoring fitness, monitoring tidur, pedometer dan masi banyak fungsi lainnya. Semua fitur ini dikemas dengan bentuk yang yang trendy dan sporty. Anda dapat melihat track record aktifitas Anda setiap harinya seperti record fitness, jumlah langkah saat berjalan, kalori, monitoring tidur dan lainnya. Hidup lebih sehat dengan memonitoring setiap aktifitas Anda.', 15, 165600, 0, 2, 'EMSM04BK;17 mm;', '1 bulan', 'Hitam', 'images/22.jpg', 0, 12, 1),
(40, 'HiMedia Mini Wireless Keyboard UKB-500', 'HiMedia', 'Mini Wireless Keyboard 92 keys, cocok untuk media player. Produk ini diproduksi dengan cermat untuk menghasilkan produk yang bermutu. Terbuat dari bahan dengan kualitas terbaik. Belilah sekarang juga. Stock terbatas, jangan sampai kehabisan.', 18, 160000, 0, 5, 'HI729ELAXU58ANID-997177;Wireless;UKB-500;17 x 12 x 3', '1 bulan', 'hitam', 'images/keyboard1.PNG', 0, 12, 1),
(41, 'Mini Wireless Remote Bluetooth Keyboard', 'OEM', 'Brand new and high quality.Compatible with Windows, Android and IOS device. The touchpad function will not work in IOS devices(Such as Iphone iPad)', 18, 331632, 0, 5, 'OE427ELBB81MANID-1174684;Wireless;UKB-500;17 x 7 x 7', 'no waranty', 'hitam', 'images/keyboard2.PNG', 0, 13, 1),
(42, 'Rexus Keyboard Gaming K7M - Hitam', 'Rexus', 'Brand new and high quality.Compatible with Windows, Android and IOS device. The touchpad function will not work in IOS devices(Such as Iphone iPad)', 18, 215000, 0, 5, 'RE257ELAIIDSANID-428859;Wireless;Keyboard Gaming;49 x 4 x 22.5', '1 bulan', 'hitam', 'images/keyboard3.PNG', 2, 13, 1),
(43, 'Razer Keyboard Blackwidow Ultimate Chroma - Hitam', 'Rexus', 'Razer Keybord Blackwidow Chroma dirancang khusus untuk para gamer,dengan fitur mekanikal baru yang memberikan kecepatan dan respons yang belum pernah anda rasakan sebelumnya.', 18, 2630000, 0, 5, 'RA824ELAJ2CAANID-461667;Wireless;Keyboard Gaming;42 x 20 x 6', '1 tahun', 'hitam', 'images/keyboard4.PNG', 3, 12, 1),
(44, 'Razer Keyboard Deathstalker Ultimate', 'Rexus', 'Razer Keybord Blackwidow Chroma dirancang khusus untuk para gamer,dengan fitur mekanikal baru yang memberikan kecepatan dan respons yang belum pernah anda rasakan sebelumnya.', 18, 3730000, 0, 5, 'RA824ELAHX28ANID-394413;Wireless;Deathstalker Ultimate T1;57 x 27 x 7', '1 tahun', 'hitam', 'images/keyboard5.PNG', 3, 12, 1),
(45, 'Logitech MK 220 Combo Keyboard - Mouse', 'Logitech', 'Logitech MK 220 Wireless Combo Keyboard & Mouse - Hitam kenyamanan Anda untuk mengetik dimana saja dengan jarak wireless 10 meter. Dengan desain yang padat, sehingga terlihat kokoh menjadikannya cocok dengan PC Anda.', 18, 233500, 0, 5, 'LO651ELADT1XANID-208180;Wireless;Deathstalker Ultimate T1;46 x 12 x 5', '1 tahun', 'hitam', 'images/keyboard6.PNG', 3, 12, 1),
(46, 'Mediatech-Wireless Keyboard-Mouse', 'Mediatech', 'Keyboard ini memiliki bentuk yang melengkung di bagian bawahnya sehingga keyboard ini akan terlihat lebih unik. Selain keyboard terdapat juga wireless mouse yang resolusinya mencapai 1600dpi dan dapat mencapai jarak 10 m baik keyboard serta mouse. Keyboard ini memiliki warna di beberapa tombolnya.', 18, 202650, 0, 5, 'ME455ELADIVDANID-192517;Wireless;Keyboard Wireless;43 x 1 x 13', '1 tahun', 'hitam', 'images/keyboard7.PNG', 3, 12, 1),
(47, 'Professional 6D 3200DPI Gaming Mouse\r\n', 'OEM', 'Product details of Professional 6D 3200DPI LED Optical Wired Gaming Mouse for Pro Gamer Excellent,100% brand new and high quality. 6 buttons with scroll wheel.\r\nEach file to switch between different colors of LED lights cool tips.\r\n', 18, 133000, 0, 3, 'OE427ELAA2HVGKANID-4586133;Wireless;Pemasangan mandiri;Mouse Kabel;Baterai;15 x 7 x 7 cm;Kabel', 'No Warranty', 'hitam', 'images/mouse1.PNG', 0, 12, 1),
(48, 'Rexus Mouse Gaming Wireless RX-110A\r\n', 'Rexus', 'MOUSE WIRELESS Rexus Rx-110 Avenger merupakan pilihan tepat untuk bermain games dan juga pemakaian sehari hari.\r\nMeskipun memiliki spesifikasi untuk para Gamers, mouse ini juga sangat cocok untuk digunakan sehari-hari dirumah, kampus maupun kantor.\r\n', 18, 98542, 0, 3, 'RE257ELBHTJAANID-1538070;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;15x10x15 cm;Wireless', 'No Warranty', 'hitam', 'images/mouse2.PNG', 1, 12, 1),
(49, '7 Button LED Wired Gaming Mouse Black\r\n', 'Rexus', 'Ergonomically designed, long-term use without fatigue. Intelligent connectivity, no need to code, plug & play\r\nBuilt-weight iron, feel comfortable, mobile and stability \r\n', 18, 108000, 0, 3, 'OE427ELBGJ1LANID-1465171;Wireless;Pemasangan mandiri;Mouse Kabel;Baterai;10 x 10 x 10 cm;Kabel', 'No Warranty', 'hitam', 'images/mouse3.PNG', 1, 12, 1),
(50, '6 Button Wireless Gaming RPortable Mouse\r\n', 'Fan Tech', 'Ergonomically designed,comfort grip. Portable and weight light, very convenient to carry and store.\r\nLeft key ,Right key ,Middle key ,Forward key,Back key ,DIP Key.', 18, 74000, 0, 3, 'NO210ELAA2SB38ANID-5164550;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;15 x 14 x 10 cm;Wireless', 'No Warranty', 'merah', 'images/mouse4.PNG', 1, 12, 1),
(51, 'Moonar USB - Wireless Mouse Car\r\n', 'Moonar', '100% brand new and high quality. USB 2.4G wireless mouse car shape, comfortable touch. Free moving in 10 meters\r\nOptical sensor up to 1600 DPI', 18, 81000, 0, 3, 'MO202ELAXI6JANID-979513;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;6 x 3 x 3 cm\r\n;Wireless', 'No Warranty', 'merah;hitam;biru', 'images/mouse5_1.PNG;images/mouse5_2.PNG;images/mouse5_3.PNG', 1, 12, 1),
(52, 'Moonar USB Wireless Optical Mouse', 'Moonar', 'Slim, ergonomically-designed 2.4 GHz wireless mouse, ideal for home or office use,Compatible with most laptop and desktop computers via USB receiver (packed in the mouse)\r\nOptical tracking technology, works on many different surfaces', 18, 64000, 0, 3, 'MO202ELAXH5HANID-977701;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;6 x 3 x 3 cm\r\n;Wireless', 'No Warranty', 'pink', 'images/mouse6.PNG', 1, 12, 1),
(53, 'Wireless Foldable Arc Optical Mouse\r\n', 'OEM', 'This Wireless Mouse is a good choice for you: up to 10m Wireless Operation Distance, Ergonomic Design, High Accuracy, High Quality, Modern Design.\r\nIdeal for office and home use.', 18, 86000, 0, 3, 'OE427ELBKAPPANID-1674435;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;6 x 3 x 3 cm\r\n;Wireless', 'No Warranty', 'hitam;abu-abu;putih', 'images/mouse7_1.PNG;images/mouse7_2.PNG;images/mouse7_3.PNG', 1, 12, 1),
(54, 'Colorful Backlight Gaming Mouse\r\n', 'OEM', 'Ultra-precise Scroll Wheel. Optical technology works on most surfaces. \r\nErgonomically designed, long-term use without fatigue.Intelligent connectivity, no need to code, plug & play.', 18, 87000, 0, 3, 'OE427ELBGJ5RANID-1465321;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;15 x 10 x 10\r\n;Wireless', 'No Warranty', 'hitam', 'images/mouse8.PNG', 1, 12, 1),
(55, 'Logitech M280 Mouse Wireless\r\n', 'Logitech', 'Anda akan mendapatkan kehandalan dan kenyaman dengan mouse nirkabel dengan transmisi data yang cepat dan tanpa hambatan.Mouse ini dilengkapi dengan switch on/off, mode penonaktifan mouse (smart sleep) \r\ndan indikator kondisi isi baterai yang dapat memperpanjang daya tahan baterai.\r\n', 18, 175000, 0, 3, 'LO651ELBN9G4ANID-1834453;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;12 x 5 x 3 cm\r\n;Wireless', '1 tahun', 'hitam;biru;merah', 'images/mouse9_1.PNG;images/mouse9_2.PNG;images/mouse9_3.PNG', 1, 13, 1),
(56, 'Logitech Mouse Wireless M238', 'Logitech', 'Sambutlah kegembiraan, kecerdasan, keberanian, dan kepribadian dengan Logitech M238 Wireless Mouse. mouse paling bahagia yang pernah Anda temukan. Hadir dengan desain yang lucu dan menggemaskan, mouse wireless persembahan dari Logitech ini sangat cocok untuk menemani Anda bekerja setiap harinya. Selain memiliki fitur yang canggih, mouse ini juga mampu mempercantik area kerja Anda berkat desain dan presisinya yang sangat baik. Dengan navigasi presisi dan kualitas Logitech,\r\nAnda tidak perlu khawatir dengan kualitas dari Logitech M238 Wireless Mouse ini.\r\n', 18, 185000, 0, 3, 'LO651ELCHQWHANID-2992702;Wireless;Pemasangan mandiri;Mouse Wireless;Baterai;9.7 x 5.5 x 3.8 cm\r\n;Wireless', '1 tahun', 'merah;biru;putih', 'images/mouse10_1.PNG;images/mouse10_2.PNG;images/mouse10_3.PNG', 1, 12, 1),
(57, 'Logitech G300s Gaming Mouse', 'Logitech', 'Masuki dunia gaming dengan menggunakan mouse Logitech Gaming G300. \r\nMouse optikal yang memberikan presisi dan bisa digunakan untuk berbagai aktivitas seperti gaming, edit gambar dan 3D modelling. Mouse ini juga kompatibell dengan berbagai sistem operasi sseperti Windows 7, \r\nVista dan XP, dan sistem operasi lain.', 18, 269000, 0, 3, 'LO651ELBP9WUANID-1949950;Kabel;Pemasangan mandiri;Mouse Kabel;Baterai;4 x 7.2 x 11.3 cm\r\n;Kabel', '3 tahun', 'hitam', 'images/mouse11.PNG', 1, 13, 1),
(58, 'Sades FlashWing Macro Gaming Mouse', 'Sades', 'Sades Flashwing Merupakan Gaming Mouse berkualitas tinggi dengan harga terjangkau, \r\nDengan Desain Modern Art dan teknologi mutakhir, Gratis Gaming MousePad Sades dan Kabel Protektor \r\n', 18, 234999, 0, 3, 'SA522ELBNEX4ANID-1841621;Kabel;Pemasangan mandiri;Mouse Kabel;Baterai;4 x 7.2 x 11.3 cm\r\n;Kabel', '3 tahun', 'hitam;putih', 'images/mouse12_1.PNG;images/mouse12_2.PNG', 2, 13, 1),
(59, 'Dragonwar - Phantom Gaming Mouse', 'Dragonwar', 'Respon anda untuk bergerak cepat dalam melakukan action dalam game memang sangat penting sehingga membutuhkan sebuah mouse yang memang di desain untuk hal itu. \r\nTersedia fungsi makro yang sangat di butuhkan untuk game-game MOBA seprti DOTA,DOTA 2, HON dan sejenisnya.\r\n', 18, 494000, 0, 3, 'DR192ELBC2CKANID-1223267;Kabel;Pemasangan mandiri;Mouse Phantom;Baterai;11 x 10 x 4 cm\r\n;Kabel', '3 tahun', 'hitam', 'images/mouse13_1.PNG', 1, 12, 1),
(60, 'Gaming Mouse For DotA', 'Dragonwar', '100% brand new and high quality.Stylish Design.Wear-resistant, anti-interference, anti-pull.\r\nBuilt-in lightweight metal, feel comfortable, mobile and stability.16-bit data path.\r\n', 18, 239000, 0, 3, 'OE427ELBGJ1WANID-1465182;Wireless;Pemasangan mandiri;Mouse Phantom;Baterai;15 x 10 x 10 cm\r\n;Wireless', 'No warranty', 'hitam', 'images/mouse14.PNG', 1, 12, 1),
(61, 'SATA Adapter Card Green', 'OEM', 'Stylish Design High quality USB connector with magnetic ring, wear-resistant, anti-interference,\r\nanti-pull Built-in lightweight metal, feel comfortable, mobile and stability 16-bit data path Most suitable for Laptop user and PC user Optical technology \r\n', 18, 445000, 0, 3, 'OE427ELBK8Y8ANID-1672070;Wireless;Pemasangan mandiri;Mouse Phantom;Baterai;15 x 10 x 10 cm\r\n;Wireless', 'No warranty', 'hitam', 'images/mouse14.PNG', 1, 12, 1),
(62, 'Xiaomi Round Bluetooth Speaker', 'xiao mi', 'Speaker dengan suara jernih dan kencang, hadir dengan design baru yang terlihat modern', 18, 258000, 0, 4, 'XI619ELBO3E1ANID-1876903;Ya;Mini USB;SPEAKER;8 x 8 x 5', '1 bulan', 'hitam', 'images/speaker1.PNG', 1, 12, 1),
(63, 'Logitech Z120 Stereo Speaker', 'logitech', 'Speaker stereo berbentuk kompak yang dibekali tenaga lewat koneksi USB ini hadir dengan pengontrol volume dan tenaga yang terintegrasi, membuatnya begitu simpel untuk terhubung dengan berbagai sumber audio. \r\nHal ini memudahkan Anda untuk menikmati musik, video dan konten multimedia lainnya.\r\n', 18, 134900, 0, 4, 'LO651ELACWBMANID-158224;Ya;Mini USB;SPEAKER;8 x 8 x 5', '1 tahun', 'hitam', 'images/speaker2.PNG', 1, 12, 1),
(64, 'Audiobox A100-U Speaker', 'Audiobox', 'Audiobox A100-U adalah speaker dengan sistem keluaran Bass-Reflex 2.2 yang memungkinkan speaker ini bisa menghasilkan suara bass yang mumpuni \r\nwalaupun dengan ukurannya yang kecil dan menggunakan daya masukan listrik dari USB. Penggunaannya yang sangat mudah, tinggal dihubungkan melalui USB dan jalankan musiknya.', 18, 110000, 0, 4, 'AU230ELAQVYYANID-600164;Ya;USB;SPEAKER;23 x 21 x 19', '1 tahun', 'hitam', 'images/speaker3.PNG', 1, 12, 1),
(65, 'Genius - Speaker SP-HF150 Wood', 'Genius', 'Get rich stereo sound in a compact wood design!  SP-HF150 is a USB powered wooden speaker with four watts of total RMS power, delivering clear vibrant sound and deep bass reverberation.', 18, 120000, 0, 4, 'GE362ELAA2AR7SANID-4251371;Ya;USB;SP-HF150;13 x 8.3 x 8.5', '1 tahun', 'hitam', 'images/speaker4.PNG', 1, 12, 1),
(66, 'Simbadda PMC 280 Portable Speaker', 'Simbadda', 'Simbadda PMC 280 Portable Speaker merupakan speaker handal persembahan dari Simbadda. Speaker ini akan menemani hari – hari istimewa Anda. Didesain dengan teknologi terkini dan para ahli dibidangnya', 18, 190000, 0, 4, 'SI876ELAWLUCANID-932188;Ya;USB;Portable Speaker;24 x 11 x 15', '1 tahun', 'putih', 'images/speaker5.PNG', 1, 12, 1),
(67, 'Simbadda Speaker CST 1200 N', 'Simbadda', 'Speaker dengan design sederhana namun elegan siap menemani anda menikmati musik kesayangan anda, dilengkapi dengan slot USB & SD Card dapat dengan mudah mendengarkan lagu langsung dari flashdisk. Desain Unik cocok diletakan di ruang santai, bahkan di kantor sekalipun.\r\n', 18, 450000, 0, 4, 'SI876ELAUWT8ANID-840563;Ya;USB;Multimedia Speaker 2.1;29 x 18 x 32', '1 tahun', 'hitam', 'images/speaker6.PNG', 3, 12, 1),
(68, 'Simbadda Portable Speaker PMC-281', 'Simbadda', 'Mendengarkan musik kesayangan anda cukup dengan menghubungkan Flash Disk / SD Card / MMC or Mobile Phone. Dapat menggunakan baterai menjadi mendengarkan musik dapat dilakukan dimana saja dan kapan saja.', 18, 235000, 0, 4, 'SI876ELBBGRSANID-1187437;Ya;USB;Portable Speaker;25 x 16 x 9', '1 bulan', 'hitam', 'images/speaker7.PNG', 3, 12, 1),
(69, 'Simbadda Speaker CST 6200 N', 'Simbadda', 'Simbadda CST 6200N dengan desain elegan dan suara yang nyaman untuk didengar. Suara bass yang dihasilkan cukup menggelegar, seimbang dengan suara treble-nya, sehingga pas untuk didengar telinga Anda.', 18, 525000, 0, 4, 'SI876ELADOQ3ANID-201402;Ya;USB;Multimedia Speaker 2.1;31 x 22 x 27', '1 bulan', 'hitam', 'images/speaker8.PNG', 4, 12, 1),
(70, 'Bluetooth Headset Two Channel', 'Two Channel', 'Bluetooth Headset with colorful style and crystal-clear sound quality. Also built with microphone and bluetooth connection so You can connect to your smartphone and other device.', 75, 99400, 0, 6, 'OMSK0PBL;0.7 kg;yes;yes;yes;This headphone compatible with any device that have bluetooth connection.', '1 bulan', 'biru;putih', 'images/bluetooth-stereo-headset-two-channel-mp3-music-headphone-bth-401-blue-1.JPG;images/bluetooth-stereo-headset-two-channel-mp3-music-headphone-bth-401-white-1.JPG', 0, 4, 1),
(71, 'Boomphones Headphones Phantom', 'Boomphones ', 'Music is a universal language that has been shared since the beginning of time, and is something the world would be lost without.\r\n\r\nAll Headphones allow you to enjoy your music in a private setting, while others allow you to engage in limited sharing capabilities.\r\n\r\nThe Boomphones Phantom offers the best of both worlds, minus the limitations. The Phantoms allow you to keep your jamming sessions private, or with the push of a button enter Boombox Mode, and share your music with the masses.', 49, 549900, 0, 6, 'BPSK02ME;2 kg;yes;yes;yes;compatible with all devices', '1 bulan', 'matte black;phantom pink;phantom blue', 'images/boomphones-handphones-phantom-matte-black-10.png;images/boomphones-handphones-phantom-pink-1.png;images/boomphones-handphones-phantom-blue-1.png', 0, 3, 1),
(72, 'Kinbas HiFi Gaming Headset with Microphone', 'Kinbas', 'Headset gaming profesional Kinbas VP-T7 yang dilengkapi dengan mic. Headset ini mengadopsi teknologi "NdFeB" HiFi yang dapat menghasilkan suara dengan kualitas yang optimal. Sangat cocok digunakan untuk bermain game, ataupun mendengarkan lagu. Headset gaming profesional Kinbas VP-T7 menggunakan bahan material anti sinar UV pada bagian body, sehingga headset akan senantiasa terlihat mengkilap dan baru. Headset gaming profesional Kinbas VP-T7 mengadopsi teknologi "NdFeB" HiFi yang dapat menghasilkan suara dengan kualitas yang optimal. Dilengkapi dengan mic, sangat cocok digunakan untuk bermain game, ataupun mendengarkan lagu. Microphone pada Headset gaming Kinbas VP-T7 ini memiliki fitur SoundSmart, dimana mic tidak akan otomatis mengeluarkan suara yang tidak Anda inginkan. Headset gaming profesional Kinbas VP-T7 ini sangat cocok digunakan untuk internet chat, VOIP (voice-over-IP), gaming, mendengarkan lagu, dll.', 34, 73900, 0, 6, 'KBSK01BL;1 kg;yes;yes;no;all devices', '1 bulan', 'blue;white;yellow;red', 'images/kinbas-high-quality-hifi-gaming-headset-with-microphone-vp-t7-blue-88.jpg;images/kinbas-high-quality-hifi-gaming-headset-with-microphone-vp-t7-white-1.jpg;images/kinbas-high-quality-hifi-gaming-headset-with-microphone-vp-t7-yellow-2.jpg;images/kinbas-high-quality-hifi-gaming-headset-with-microphone-vp-t7-white-1_-_Copy.jpg', 0, 2, 1),
(73, 'Transcend Micro SDHC 16GB', 'Transcend', 'Saat ini kamera digital, smartphone, tablet memiliki spesifikasi yang tinggi dan cepat, membutuhkan media penyimpanan yang tinggi serta kemampuan menyimpan konten resolusi tinggi. Oleh sebab itu dibutuhkan dukungan media penyimpanan yang mampu mengimbangi kebutuhan tersebut. Transcend microSDHC Class 10 merupakan penyimpanan yang mampu mengatasi hal tersebut. Menawarkan kapasitas yang besar serta kecepatan superior hingga 30 MB/detik. Mendukung penuh kecepatan Class 10, Transcend microSDHC Class 10 menggunakan teknologi terbaru untuk memaksimalkan waktu respon perangkat elektronik Anda. Dengan kecepatan baca dan tulis hingga 30 Mb/s menawarkan kemampuan merekam video Full HD dengan sempurna serta menjalankan aplikasi dengan lancar pada smartphone.', 58, 49300, 0, 7, 'TR942ELAA59OCXANID-10605419;11 x 15 x 1;0.4 kg;yes', '1 Tahun', 'hitam', 'images/transcend-micro-sdhc-16gb-class10-tidak-termasuk-adaptor-4957-3559488-a5feb1bebd758906ea807af74aca36ea-webp-zoom.jpg', 0, 4, 1),
(74, 'SanDisk Ultra microSDHC Card 48MB/s 16GB', 'SanDisk', 'SanDisk Ultra microSDHC UHS-I Card adalah kartu memori UHS-I dengan kecepatan class 10 yang dapat digunakan untuk pengambilan video dengan kualitas Full HD pada perangkat smartphone ataupun tablet milik Anda. Dengan kecepatan transfer sampai dengan 48MB/s, kartu memori ini menawarkan kepada Anda kecepatan pemindahan file yang cepat untuk memindahkan data antara PC dan smartphone atau tablet Anda. Tambahkan kapasitas memori di perangkat Android, smartphone, tablet ataupun kamera Anda dengan SanDisk Ultra microSDHC UHS-I Card. Dengan kecepatan class 10 membuatnya ideal untuk mengambil video Full HD. Peningkatan kecepatan transfer sampai dengan 48MB/s membuat waktu loading aplikasi atau file pada perangkat mobile Anda. Dengan berbagai pilihan kapasitas, Anda dapat memilih sesuai dengan kebutuhan. SanDisk merancang kartu memori microSDHC ini untuk berbagai kondisi. Kartu memori ini anti air dan telah diuji dan dapat bertahan hingga 72 jam di air asin maupun air tawar dalam kedalaman 1 meter. Tak hanya itu, kartu memori ini juga anti guncangan dan dapat menahan guncangan hingga 500Gs. Anda pun dapat membawa SanDisk Ultra microSDHC UHS-I Card di berbagai kondisi cuaca karena tahan suhu dari -13 hingga 185 derajat Fahrenheit.', 24, 64900, 0, 7, 'SA850ELCFHBUANID-2865218;1.1 x 0.5 x 1.5;0.1 kg;yes', 'Seumur Hidup', 'putih', 'images/sandisk-ultra-microsdhc-card-uhs-i-class-10-48mb-s-16gb-5518-7203432-1-webp-zoom.jpg', 0, 0, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `barang`
--
ALTER TABLE `barang`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `barang`
--
ALTER TABLE `barang`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
